autogen: updated common files in xdeli

diff --git a/.github/workflows/xdeli-project-common.yml b/.github/workflows/xdeli-project-common.yml
--- a/.github/workflows/xdeli-project-common.yml
+++ b/.github/workflows/xdeli-project-common.yml
@@ -14,6 +14,15 @@ env:
   unread: 📥 Unread
   org: xdeli-tech
   project_id: 3
+  ORG_NAME: xdeli-tech
+  STRICT_REPO_LIST: |
+    xdeli-tech/iemeci-aws-infrastructure
+    xdeli-tech/delivery-provider-skeleton
+    xdeli-tech/delivery-provider
+    xdeli-tech/delivery-provider-ubereats
+    xdeli-tech/delivery-provider-demaecan
+    xdeli-tech/rpa_ai
+    xdeli-tech/xdeli-web-app
 
 concurrency:
   group: project-common-${{ github.ref }}
@@ -105,3 +114,67 @@ jobs:
           exclude-branches: 'release/**, dependabot/**, project-common/**'
           github-token: ${{ env.PJ_GH_BOT_TOKEN }}
           loose-matching: true
+
+    branches-ignore:
+      - main
+
+
+  create_and_enable_automerge:
+    runs-on: ubuntu-latest
+    timeout-minutes: 1
+    if: >-
+      (github.event_name == 'push')
+      && (github.ref != 'refs/heads/main')
+      && contains(split(env.STRICT_REPO_LIST, '\n'), github.repository)
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+      - name: Set branch name as output
+        id: branch_name
+        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
+
+      - name: Create Pull Request
+        id: create_pr
+        uses: repo-sync/pull-request@v2
+        with:
+          github_token: ${{ secrets.XDELI_BOT_TOKEN }}
+          destination_branch: 'main'
+          source_branch: ''
+          pr_title: '${{ steps.branch_name.outputs.branch }}'
+          pr_body: ':magic_wand: :sparkles:'
+          pr_draft: false
+
+      - name: Assign PR to author
+        if: steps.create_pr.outputs.pr_number
+        uses: octokit/request-action@v2.x
+        with:
+          route: POST /repos/${{ github.repository }}/issues/${{ steps.create_pr.outputs.pr_number }}/assignees
+          assignees: ${{ github.actor }}
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Get PR Node ID
+        if: steps.create_pr.outputs.pr_number
+        id: get_pr_id
+        run: |
+          PR_DATA=$(curl -s -H "Authorization: token ${{ secrets.XDELI_BOT_TOKEN }}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/${{ github.repository }}/pulls/${{ steps.create_pr.outputs.pr_number }}")
+          PR_ID=$(echo "$PR_DATA" | jq -r '.node_id')
+          echo "::set-output name=node_id::$PR_ID"
+
+      - name: Enable Auto Merge for PR
+        if: steps.create_pr.outputs.pr_number
+        run: |
+          RESPONSE=$(curl -s -X POST \
+            -H "Authorization: bearer ${{ secrets.XDELI_BOT_TOKEN }}" \
+            -H "Content-Type: application/json" \
+            -d '{
+              "query": "mutation($id: ID!) { enablePullRequestAutoMerge(input: { pullRequestId: $id }) { clientMutationId } }",
+              "variables": {
+                "id": "'"${{ steps.get_pr_id.outputs.node_id }}"'"
+              }
+            }' \
+            "https://api.github.com/graphql")
+          echo "$RESPONSE"
+          if echo "$RESPONSE" | jq -e '.errors' >/dev/null; then
+            echo "Failed to enable auto merge"
+            exit 1
+          fi
